id: eeuq-0012
title: Seismic Wave Basin Effects Model (DRM Example)
summary: This example demonstrates the effect of a semi-hemispherical sedimentary basin on seismic wave propagation using the Domain Reduction Method (DRM) in EE-UQ, based on Femora Example 3.
